# Generated by Django 4.2.3 on 2023-08-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('article_content', models.CharField(default='Default content', max_length=5000)),
                ('creation_time', models.DateTimeField()),
                ('webpage', models.CharField(max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('news_website', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=15, null=True)),
                ('Managing_Editor', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('comment_content', models.CharField(max_length=1000)),
                ('creation_time', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_article.article')),
            ],
        ),
    ]
