# Generated by Django 4.2.3 on 2023-08-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0002_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
