# Generated by Django 4.2.3 on 2023-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0003_alter_comment_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
